### ISSUE TITLE
Unable to install via apt-get on Pi4 / Buster

### ISSUE THREAD

**Issue by AlistairFielden** [tobyweston/temperature-machine-ui#3] opened 2019-07-13 16:33 UTC
Getting the following message when I try to 'sudo apt-get update' having added the repository into sources.list. This is on the new Raspberry Pi 4.

Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Ign:3 http://robotooling.com/debian ./ InRelease
Err:4 http://robotooling.com/debian ./ Release
  404  Not Found [IP: 192.30.252.153 80]
Reading package lists... Done
E: The repository 'http://robotooling.com/debian ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (en_GB) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5

**Comment by tobyweston** [comment] 2019-07-16 10:47
This is a duplicate of https://github.com/tobyweston/temperature-machine/issues/84

This project is about the UI and the problem relates more to the server / main application, so closing this issue and tracking over there.

**Closed as completed by tobyweston** 2019-07-16 10:47 UTC

**Comment by tobyweston** [comment] 2019-07-16 10:53
When I've seen this in the past, there's usually an option to install anyway (despite the warnings), you'd have to accept with a `Y` character or similar. Is that the case above or does it just fail and not allow you to install?

Also see https://askubuntu.com/questions/732985/force-update-from-unsigned-repository-ubuntu-16-04 to try overriding the restriction.

Something like `apt-get --allow-unauthenticated install ...`
